// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreatePersonRequest struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePersonRequest) Reset()         { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()    {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreatePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonRequest.Unmarshal(m, b)
}
func (m *CreatePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonRequest.Marshal(b, m, deterministic)
}
func (m *CreatePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonRequest.Merge(m, src)
}
func (m *CreatePersonRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePersonRequest.Size(m)
}
func (m *CreatePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonRequest proto.InternalMessageInfo

func (m *CreatePersonRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type CreatePersonResponse struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePersonResponse) Reset()         { *m = CreatePersonResponse{} }
func (m *CreatePersonResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePersonResponse) ProtoMessage()    {}
func (*CreatePersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreatePersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonResponse.Unmarshal(m, b)
}
func (m *CreatePersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonResponse.Marshal(b, m, deterministic)
}
func (m *CreatePersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonResponse.Merge(m, src)
}
func (m *CreatePersonResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePersonResponse.Size(m)
}
func (m *CreatePersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonResponse proto.InternalMessageInfo

func (m *CreatePersonResponse) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type ReadPersonRequest struct {
	PersonId             string   `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPersonRequest) Reset()         { *m = ReadPersonRequest{} }
func (m *ReadPersonRequest) String() string { return proto.CompactTextString(m) }
func (*ReadPersonRequest) ProtoMessage()    {}
func (*ReadPersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ReadPersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPersonRequest.Unmarshal(m, b)
}
func (m *ReadPersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPersonRequest.Marshal(b, m, deterministic)
}
func (m *ReadPersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPersonRequest.Merge(m, src)
}
func (m *ReadPersonRequest) XXX_Size() int {
	return xxx_messageInfo_ReadPersonRequest.Size(m)
}
func (m *ReadPersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPersonRequest proto.InternalMessageInfo

func (m *ReadPersonRequest) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

type ReadPersonResponse struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPersonResponse) Reset()         { *m = ReadPersonResponse{} }
func (m *ReadPersonResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPersonResponse) ProtoMessage()    {}
func (*ReadPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ReadPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPersonResponse.Unmarshal(m, b)
}
func (m *ReadPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPersonResponse.Marshal(b, m, deterministic)
}
func (m *ReadPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPersonResponse.Merge(m, src)
}
func (m *ReadPersonResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPersonResponse.Size(m)
}
func (m *ReadPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPersonResponse proto.InternalMessageInfo

func (m *ReadPersonResponse) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type UpdatePersonRequest struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePersonRequest) Reset()         { *m = UpdatePersonRequest{} }
func (m *UpdatePersonRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePersonRequest) ProtoMessage()    {}
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *UpdatePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePersonRequest.Unmarshal(m, b)
}
func (m *UpdatePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePersonRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePersonRequest.Merge(m, src)
}
func (m *UpdatePersonRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePersonRequest.Size(m)
}
func (m *UpdatePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePersonRequest proto.InternalMessageInfo

func (m *UpdatePersonRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type UpdatePersonResponse struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePersonResponse) Reset()         { *m = UpdatePersonResponse{} }
func (m *UpdatePersonResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePersonResponse) ProtoMessage()    {}
func (*UpdatePersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *UpdatePersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePersonResponse.Unmarshal(m, b)
}
func (m *UpdatePersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePersonResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePersonResponse.Merge(m, src)
}
func (m *UpdatePersonResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePersonResponse.Size(m)
}
func (m *UpdatePersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePersonResponse proto.InternalMessageInfo

func (m *UpdatePersonResponse) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type DeletePersonRequest struct {
	PersonId             string   `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePersonRequest) Reset()         { *m = DeletePersonRequest{} }
func (m *DeletePersonRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePersonRequest) ProtoMessage()    {}
func (*DeletePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *DeletePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePersonRequest.Unmarshal(m, b)
}
func (m *DeletePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePersonRequest.Marshal(b, m, deterministic)
}
func (m *DeletePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePersonRequest.Merge(m, src)
}
func (m *DeletePersonRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePersonRequest.Size(m)
}
func (m *DeletePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePersonRequest proto.InternalMessageInfo

func (m *DeletePersonRequest) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

type DeletePersonResponse struct {
	PersonId             string   `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePersonResponse) Reset()         { *m = DeletePersonResponse{} }
func (m *DeletePersonResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePersonResponse) ProtoMessage()    {}
func (*DeletePersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *DeletePersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePersonResponse.Unmarshal(m, b)
}
func (m *DeletePersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePersonResponse.Marshal(b, m, deterministic)
}
func (m *DeletePersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePersonResponse.Merge(m, src)
}
func (m *DeletePersonResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePersonResponse.Size(m)
}
func (m *DeletePersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePersonResponse proto.InternalMessageInfo

func (m *DeletePersonResponse) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SignupRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UsernameUsedRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameUsedRequest) Reset()         { *m = UsernameUsedRequest{} }
func (m *UsernameUsedRequest) String() string { return proto.CompactTextString(m) }
func (*UsernameUsedRequest) ProtoMessage()    {}
func (*UsernameUsedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *UsernameUsedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameUsedRequest.Unmarshal(m, b)
}
func (m *UsernameUsedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameUsedRequest.Marshal(b, m, deterministic)
}
func (m *UsernameUsedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameUsedRequest.Merge(m, src)
}
func (m *UsernameUsedRequest) XXX_Size() int {
	return xxx_messageInfo_UsernameUsedRequest.Size(m)
}
func (m *UsernameUsedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameUsedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameUsedRequest proto.InternalMessageInfo

func (m *UsernameUsedRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type EmailUsedRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailUsedRequest) Reset()         { *m = EmailUsedRequest{} }
func (m *EmailUsedRequest) String() string { return proto.CompactTextString(m) }
func (*EmailUsedRequest) ProtoMessage()    {}
func (*EmailUsedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *EmailUsedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailUsedRequest.Unmarshal(m, b)
}
func (m *EmailUsedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailUsedRequest.Marshal(b, m, deterministic)
}
func (m *EmailUsedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailUsedRequest.Merge(m, src)
}
func (m *EmailUsedRequest) XXX_Size() int {
	return xxx_messageInfo_EmailUsedRequest.Size(m)
}
func (m *EmailUsedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailUsedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailUsedRequest proto.InternalMessageInfo

func (m *EmailUsedRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UsedResponse struct {
	Used                 bool     `protobuf:"varint,1,opt,name=Used,proto3" json:"Used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsedResponse) Reset()         { *m = UsedResponse{} }
func (m *UsedResponse) String() string { return proto.CompactTextString(m) }
func (*UsedResponse) ProtoMessage()    {}
func (*UsedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *UsedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsedResponse.Unmarshal(m, b)
}
func (m *UsedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsedResponse.Marshal(b, m, deterministic)
}
func (m *UsedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsedResponse.Merge(m, src)
}
func (m *UsedResponse) XXX_Size() int {
	return xxx_messageInfo_UsedResponse.Size(m)
}
func (m *UsedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsedResponse proto.InternalMessageInfo

func (m *UsedResponse) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

type AuthUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserRequest) Reset()         { *m = AuthUserRequest{} }
func (m *AuthUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthUserRequest) ProtoMessage()    {}
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *AuthUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserRequest.Unmarshal(m, b)
}
func (m *AuthUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserRequest.Marshal(b, m, deterministic)
}
func (m *AuthUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserRequest.Merge(m, src)
}
func (m *AuthUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthUserRequest.Size(m)
}
func (m *AuthUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserRequest proto.InternalMessageInfo

func (m *AuthUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthUserResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserResponse) Reset()         { *m = AuthUserResponse{} }
func (m *AuthUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthUserResponse) ProtoMessage()    {}
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *AuthUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserResponse.Unmarshal(m, b)
}
func (m *AuthUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserResponse.Marshal(b, m, deterministic)
}
func (m *AuthUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserResponse.Merge(m, src)
}
func (m *AuthUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthUserResponse.Size(m)
}
func (m *AuthUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserResponse proto.InternalMessageInfo

func (m *AuthUserResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AuthUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "proto.Person")
	proto.RegisterType((*CreatePersonRequest)(nil), "proto.CreatePersonRequest")
	proto.RegisterType((*CreatePersonResponse)(nil), "proto.CreatePersonResponse")
	proto.RegisterType((*ReadPersonRequest)(nil), "proto.ReadPersonRequest")
	proto.RegisterType((*ReadPersonResponse)(nil), "proto.ReadPersonResponse")
	proto.RegisterType((*UpdatePersonRequest)(nil), "proto.UpdatePersonRequest")
	proto.RegisterType((*UpdatePersonResponse)(nil), "proto.UpdatePersonResponse")
	proto.RegisterType((*DeletePersonRequest)(nil), "proto.DeletePersonRequest")
	proto.RegisterType((*DeletePersonResponse)(nil), "proto.DeletePersonResponse")
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
	proto.RegisterType((*SignupRequest)(nil), "proto.SignupRequest")
	proto.RegisterType((*UsernameUsedRequest)(nil), "proto.UsernameUsedRequest")
	proto.RegisterType((*EmailUsedRequest)(nil), "proto.EmailUsedRequest")
	proto.RegisterType((*UsedResponse)(nil), "proto.UsedResponse")
	proto.RegisterType((*AuthUserRequest)(nil), "proto.AuthUserRequest")
	proto.RegisterType((*AuthUserResponse)(nil), "proto.AuthUserResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x55, 0xb3, 0xb6, 0x4a, 0xdf, 0xd2, 0x31, 0x9c, 0x88, 0x95, 0xec, 0x82, 0x2c, 0x10, 0x3b,
	0xa0, 0x89, 0xb5, 0x27, 0xb4, 0x21, 0x98, 0x28, 0xaa, 0x2a, 0x71, 0x98, 0xda, 0xf5, 0x88, 0x50,
	0x20, 0xd6, 0x88, 0xd8, 0x9a, 0x10, 0xa7, 0xf0, 0x27, 0xf9, 0x51, 0x28, 0xb6, 0xe3, 0xda, 0xad,
	0x99, 0x56, 0x71, 0x4a, 0xbe, 0xcf, 0xdf, 0xfb, 0xde, 0xb3, 0xf5, 0x1e, 0xfa, 0x9c, 0x95, 0xbf,
	0xb2, 0x6f, 0xec, 0xb4, 0x28, 0xf3, 0x2a, 0x27, 0x1d, 0xf1, 0xa1, 0xaf, 0xd0, 0xbd, 0x62, 0x25,
	0xcf, 0x97, 0xe4, 0x00, 0x5e, 0x96, 0x0e, 0x5a, 0xcf, 0x5a, 0x27, 0xbd, 0x99, 0x97, 0xa5, 0x84,
	0xa0, 0xbd, 0x4c, 0xee, 0xd8, 0xc0, 0x13, 0x1d, 0xf1, 0x4f, 0x2f, 0x10, 0x7e, 0x28, 0x59, 0x52,
	0x31, 0x89, 0x99, 0xb1, 0x9f, 0x2b, 0xc6, 0x2b, 0xf2, 0x02, 0xdd, 0x42, 0x34, 0x04, 0x7c, 0x7f,
	0xd8, 0x97, 0x1c, 0xa7, 0x6a, 0x4a, 0x1d, 0xd2, 0xb7, 0x88, 0x6c, 0x34, 0x2f, 0xf2, 0x25, 0x67,
	0x0f, 0x85, 0xbf, 0xc6, 0xe3, 0x19, 0x4b, 0x52, 0x9b, 0xfa, 0x18, 0x3d, 0x79, 0xfc, 0x45, 0x8b,
	0xf7, 0x65, 0x63, 0x9a, 0xd2, 0x73, 0x10, 0x13, 0xb1, 0x1b, 0xdd, 0x05, 0xc2, 0x45, 0x91, 0xfe,
	0xc7, 0x5d, 0x6d, 0xf4, 0x6e, 0xe4, 0x43, 0x84, 0x63, 0x76, 0xcb, 0x36, 0xc9, 0xef, 0xbd, 0xed,
	0x08, 0x91, 0x8d, 0x51, 0x94, 0xf7, 0x82, 0xde, 0x23, 0xf8, 0x94, 0xdf, 0x64, 0x9a, 0x21, 0x42,
	0x47, 0xd4, 0x6a, 0x50, 0x16, 0x24, 0x86, 0x7f, 0x95, 0x70, 0xfe, 0x3b, 0x2f, 0x53, 0xe5, 0x07,
	0x5d, 0xd3, 0xe7, 0x08, 0x2e, 0x57, 0xd5, 0x77, 0x4d, 0x17, 0xa1, 0x73, 0x9d, 0xff, 0x60, 0x7a,
	0x83, 0x28, 0xe8, 0x67, 0xf4, 0xe7, 0xd9, 0xcd, 0x72, 0x55, 0x34, 0x44, 0x31, 0xfc, 0x05, 0x67,
	0xa5, 0xb0, 0x98, 0x12, 0xd5, 0xd4, 0xf5, 0x8a, 0x8f, 0x77, 0x49, 0x76, 0xab, 0xb8, 0x64, 0x61,
	0x89, 0xd8, 0xdb, 0x10, 0x71, 0x86, 0xb0, 0x41, 0x2f, 0x38, 0x4b, 0x1f, 0x40, 0x42, 0x4f, 0x70,
	0x28, 0xf6, 0x9a, 0xf3, 0x9a, 0xb8, 0x65, 0x10, 0x53, 0x8a, 0x40, 0x0e, 0xa9, 0x1b, 0x12, 0xb4,
	0xeb, 0x5a, 0x0c, 0xf9, 0x33, 0xf1, 0x4f, 0x5f, 0xe2, 0x51, 0xfd, 0x0a, 0xf5, 0x76, 0x63, 0x99,
	0xe3, 0x21, 0xae, 0x71, 0xb8, 0x1e, 0x54, 0x0b, 0x0f, 0xe0, 0x4d, 0xc7, 0x4d, 0xf4, 0xa6, 0x63,
	0x4b, 0xb6, 0xf7, 0xaf, 0xb7, 0xd9, 0x33, 0x24, 0x0e, 0xff, 0xb4, 0xb1, 0x3f, 0xaf, 0x58, 0x35,
	0x97, 0x19, 0x27, 0x13, 0x04, 0x66, 0xd4, 0x48, 0xac, 0x6c, 0xe6, 0x48, 0x6f, 0x7c, 0xec, 0x3c,
	0x53, 0xd2, 0x2e, 0x81, 0x75, 0x84, 0xc8, 0x40, 0x8d, 0x6e, 0xe5, 0x30, 0x7e, 0xea, 0x38, 0x51,
	0x2b, 0x26, 0x08, 0xcc, 0x28, 0x68, 0x2d, 0x8e, 0x74, 0x69, 0x2d, 0xce, 0xec, 0x4c, 0x10, 0x98,
	0x06, 0xd7, 0x8b, 0x1c, 0x49, 0xd1, 0x8b, 0x9c, 0x89, 0x38, 0x53, 0x26, 0x27, 0xa1, 0x9a, 0x32,
	0x23, 0x10, 0x37, 0x4d, 0xcb, 0xd5, 0x23, 0x74, 0xa5, 0x7f, 0x49, 0xa4, 0x8e, 0x2d, 0x3b, 0xbb,
	0x41, 0xef, 0x84, 0x71, 0xb4, 0x2b, 0xd7, 0x37, 0xdf, 0xb6, 0xaa, 0x5e, 0x60, 0x39, 0xed, 0x0d,
	0x7a, 0xda, 0xa3, 0xe4, 0x48, 0x4d, 0x6c, 0xba, 0xd6, 0x0d, 0x3d, 0x87, 0xdf, 0xf8, 0x8c, 0x3c,
	0x31, 0xc4, 0x19, 0x0e, 0x8d, 0x8f, 0xb6, 0xfa, 0x12, 0xfc, 0xb5, 0x2b, 0xfa, 0xa3, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x72, 0xae, 0xc8, 0x4e, 0x34, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StetServiceClient is the client API for StetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StetServiceClient interface {
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error)
	ReadPerson(ctx context.Context, in *ReadPersonRequest, opts ...grpc.CallOption) (*ReadPersonResponse, error)
	UpdatePerson(ctx context.Context, in *UpdatePersonRequest, opts ...grpc.CallOption) (*UpdatePersonResponse, error)
	DeletePerson(ctx context.Context, in *DeletePersonRequest, opts ...grpc.CallOption) (*DeletePersonResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	UsernameUsed(ctx context.Context, in *UsernameUsedRequest, opts ...grpc.CallOption) (*UsedResponse, error)
	EmailUsed(ctx context.Context, in *EmailUsedRequest, opts ...grpc.CallOption) (*UsedResponse, error)
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error)
}

type stetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStetServiceClient(cc grpc.ClientConnInterface) StetServiceClient {
	return &stetServiceClient{cc}
}

func (c *stetServiceClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error) {
	out := new(CreatePersonResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/CreatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) ReadPerson(ctx context.Context, in *ReadPersonRequest, opts ...grpc.CallOption) (*ReadPersonResponse, error) {
	out := new(ReadPersonResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/ReadPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) UpdatePerson(ctx context.Context, in *UpdatePersonRequest, opts ...grpc.CallOption) (*UpdatePersonResponse, error) {
	out := new(UpdatePersonResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/UpdatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) DeletePerson(ctx context.Context, in *DeletePersonRequest, opts ...grpc.CallOption) (*DeletePersonResponse, error) {
	out := new(DeletePersonResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/DeletePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) UsernameUsed(ctx context.Context, in *UsernameUsedRequest, opts ...grpc.CallOption) (*UsedResponse, error) {
	out := new(UsedResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/UsernameUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) EmailUsed(ctx context.Context, in *EmailUsedRequest, opts ...grpc.CallOption) (*UsedResponse, error) {
	out := new(UsedResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/EmailUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stetServiceClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error) {
	out := new(AuthUserResponse)
	err := c.cc.Invoke(ctx, "/proto.StetService/AuthUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StetServiceServer is the server API for StetService service.
type StetServiceServer interface {
	CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error)
	ReadPerson(context.Context, *ReadPersonRequest) (*ReadPersonResponse, error)
	UpdatePerson(context.Context, *UpdatePersonRequest) (*UpdatePersonResponse, error)
	DeletePerson(context.Context, *DeletePersonRequest) (*DeletePersonResponse, error)
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	Signup(context.Context, *SignupRequest) (*AuthResponse, error)
	UsernameUsed(context.Context, *UsernameUsedRequest) (*UsedResponse, error)
	EmailUsed(context.Context, *EmailUsedRequest) (*UsedResponse, error)
	AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error)
}

// UnimplementedStetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStetServiceServer struct {
}

func (*UnimplementedStetServiceServer) CreatePerson(ctx context.Context, req *CreatePersonRequest) (*CreatePersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePerson not implemented")
}
func (*UnimplementedStetServiceServer) ReadPerson(ctx context.Context, req *ReadPersonRequest) (*ReadPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPerson not implemented")
}
func (*UnimplementedStetServiceServer) UpdatePerson(ctx context.Context, req *UpdatePersonRequest) (*UpdatePersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePerson not implemented")
}
func (*UnimplementedStetServiceServer) DeletePerson(ctx context.Context, req *DeletePersonRequest) (*DeletePersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePerson not implemented")
}
func (*UnimplementedStetServiceServer) Login(ctx context.Context, req *LoginRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedStetServiceServer) Signup(ctx context.Context, req *SignupRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedStetServiceServer) UsernameUsed(ctx context.Context, req *UsernameUsedRequest) (*UsedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameUsed not implemented")
}
func (*UnimplementedStetServiceServer) EmailUsed(ctx context.Context, req *EmailUsedRequest) (*UsedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailUsed not implemented")
}
func (*UnimplementedStetServiceServer) AuthUser(ctx context.Context, req *AuthUserRequest) (*AuthUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUser not implemented")
}

func RegisterStetServiceServer(s *grpc.Server, srv StetServiceServer) {
	s.RegisterService(&_StetService_serviceDesc, srv)
}

func _StetService_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/CreatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).CreatePerson(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_ReadPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).ReadPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/ReadPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).ReadPerson(ctx, req.(*ReadPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_UpdatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).UpdatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/UpdatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).UpdatePerson(ctx, req.(*UpdatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_DeletePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).DeletePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/DeletePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).DeletePerson(ctx, req.(*DeletePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_UsernameUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameUsedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).UsernameUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/UsernameUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).UsernameUsed(ctx, req.(*UsernameUsedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_EmailUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailUsedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).EmailUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/EmailUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).EmailUsed(ctx, req.(*EmailUsedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StetService_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StetServiceServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StetService/AuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StetServiceServer).AuthUser(ctx, req.(*AuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StetService",
	HandlerType: (*StetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _StetService_CreatePerson_Handler,
		},
		{
			MethodName: "ReadPerson",
			Handler:    _StetService_ReadPerson_Handler,
		},
		{
			MethodName: "UpdatePerson",
			Handler:    _StetService_UpdatePerson_Handler,
		},
		{
			MethodName: "DeletePerson",
			Handler:    _StetService_DeletePerson_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _StetService_Login_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _StetService_Signup_Handler,
		},
		{
			MethodName: "UsernameUsed",
			Handler:    _StetService_UsernameUsed_Handler,
		},
		{
			MethodName: "EmailUsed",
			Handler:    _StetService_EmailUsed_Handler,
		},
		{
			MethodName: "AuthUser",
			Handler:    _StetService_AuthUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
